Makes the blacklist more clear
paulzhng/UCUtils pull request #31
Opened 2021-05-13 18:40 UTC by Dimiikou

Appends modifiers to the blacklist instead of prepend

2021-05-15 21:12 UTC, paulzhng requested changes

2021-05-15 21:12 UTC, paulzhng commented on src/main/java/de/fuzzlemann/ucutils/commands/faction/badfaction/blacklist/ModifyBlacklistCommand.java
> +                TextUtils.error("Der Spieler ist bereits Vogelfrei.");
"vogelfrei" should be written in lower case

2021-05-15 21:12 UTC, paulzhng commented on src/main/java/de/fuzzlemann/ucutils/commands/faction/badfaction/blacklist/ModifyBlacklistCommand.java
> +        reason = reason.replace(" [Yobannoe dno]", "") // Removes Yobbanoe dno modifier
can be replaced with a Regex removing everything in brackets, e.g. `(:?\[|\().+(:?\]|\))`

2021-05-15 23:52 UTC, Dimiikou commented on src/main/java/de/fuzzlemann/ucutils/commands/faction/badfaction/blacklist/ModifyBlacklistCommand.java
> +                TextUtils.error("Der Spieler ist bereits Vogelfrei.");
contains is case sensitive, so why should we wake it lower case, if we append the reason with an uppercase letter

2021-05-15 23:55 UTC, paulzhng commented on src/main/java/de/fuzzlemann/ucutils/commands/faction/badfaction/blacklist/ModifyBlacklistCommand.java
> +                TextUtils.error("Der Spieler ist bereits Vogelfrei.");
I'm talking about the message `TextUtils.error(#)`

2021-05-15 23:56 UTC, Dimiikou commented on src/main/java/de/fuzzlemann/ucutils/commands/faction/badfaction/blacklist/ModifyBlacklistCommand.java
> +        reason = reason.replace(" [Yobannoe dno]", "") // Removes Yobbanoe dno modifier
Done

2021-05-15 23:56 UTC, Dimiikou commented on src/main/java/de/fuzzlemann/ucutils/commands/faction/badfaction/blacklist/ModifyBlacklistCommand.java
> +                TextUtils.error("Der Spieler ist bereits Vogelfrei.");
Also done

2021-05-16 10:37 UTC, paulzhng approved these changes

2021-05-16 10:38 UTC, merged