Fixxes an issue which caused players getting kicked for spamming
paulzhng/UCUtils pull request #6
Opened 2021-02-07 03:03 UTC by Dimiikou

https://github.com/paulzhng/UCUtils/issues/4

Fixxes this issue

2021-02-07 09:31 UTC, paulzhng requested changes
In general, this idea is a good one. I have a problem with how it's done. I would much rather do a one second rate-limit. Also, the implementation is way too resource-heavy for what it actually does. The same can be achieved by using a `long` storing the current time and calculating the elapsed time, returning when it's not over one minute.

2021-02-07 18:12 UTC, Dimiikou commented
Changed it the way you asked

2021-02-08 23:13 UTC, paulzhng requested changes

2021-02-08 23:13 UTC, paulzhng commented on src/main/java/de/fuzzlemann/ucutils/events/ReviveEventHandler.java
> +    private static long latestEcecute = -1;
rename to latestExecute

2021-02-08 23:13 UTC, paulzhng commented on src/main/java/de/fuzzlemann/ucutils/events/ReviveEventHandler.java
>              if (distance < 2) {
please don't nest two if's. Invert this statement & execute return if `distance >= 2`

2021-02-08 23:13 UTC, paulzhng commented on src/main/java/de/fuzzlemann/ucutils/utils/faction/badfaction/speech/SpeechModifyUtil.java
> -            String toReplace = entry.getKey();
this doesn't fit in this PR

2021-02-09 08:45 UTC, Dimiikou commented on src/main/java/de/fuzzlemann/ucutils/utils/faction/badfaction/speech/SpeechModifyUtil.java
> -            String toReplace = entry.getKey();
> this doesn't fit in this PR

How do i remove this class from this PR?

2021-02-09 08:49 UTC, paulzhng commented on src/main/java/de/fuzzlemann/ucutils/utils/faction/badfaction/speech/SpeechModifyUtil.java
> -            String toReplace = entry.getKey();
Revert it

2021-02-09 18:51 UTC, Dimiikou commented
Reverted the Changes, reduced to one if and corrected the missspell

2021-02-10 08:45 UTC, paulzhng commented
Changes in SpeechyModifyUtil still aren't reverted

2021-02-10 13:19 UTC, Dimiikou commented
But now!

2021-02-10 15:53 UTC, paulzhng commented on src/main/java/de/fuzzlemann/ucutils/events/ReviveEventHandler.java
> +            if (distance >= 2 && System.currentTimeMillis() - latestExecute < 5000) return;
To be honest, I'd lower the cooldown to 500ms or something. Just a QOL change

2021-02-10 16:07 UTC, Dimiikou commented on src/main/java/de/fuzzlemann/ucutils/events/ReviveEventHandler.java
> +            if (distance >= 2 && System.currentTimeMillis() - latestExecute < 5000) return;
Reduced the cooldown to 500ms

2021-02-10 16:24 UTC, paulzhng approved these changes
LGTM

2021-02-10 16:24 UTC, merged